### PR TITLE
💚 GH workflow CI

### PR DESCRIPTION
**Pull request by ctcpip**

### CODE REVIEW

**Comment by ctcpip** [comment]
passing:  https://github.com/ctcpip/basic-auth-connect/actions/runs/9305926068

**Comment by ctcpip** [comment]
should also add the deprecated flag on the next publish

**Review by UlisesGascon — APPROVED** [review]
LGTM!

**Comment by UlisesGascon** [comment]
I will merge it w/o waiting 2 working days, as we need this CI running asap :+1:

**Pull request merged**
